### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [kumarchandan/cfc#1]
that's a broken logic: https://github.com/kumarchandan/cfc/blob/572262ab22d4473b26779641570bbb48872d620c/manager/db/query.js#L269

it calls `callback` with data and error in the same way, so the recipient cannot know the difference.

**Comment by kumarchandan** [comment]
@vitaly-t thanks for pointing it out..so should i handle the error in caller function or throw an error in `catch {}` itself?

**Comment by vitaly-t** [comment]
throwing there won't help, handling - in any way you want ;)

**Comment by kumarchandan** [comment]
@vitaly-t Done! Thanks a lot for your time! and really good job done in pg-promise. :+1:
